services:
  api:
    container_name: crontainer-api
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - crontainer-data:/app/data
    environment:
      DEBUG: False
      CRONTAB_PATH: "/etc/cron.d"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "admin"

  frontend:
    container_name: crontainer-frontend
    build: ./frontend
    ports:
      - "9090:80"
    depends_on:
      - api

volumes:
  crontainer-data:
