[project]
name = "crontainer"
version = "0.1.0"
description = "Schedule and manage Docker containers with cron."
requires-python = ">=3.12"
dependencies = [
    "Django==5.2.1",
    "cron-descriptor==1.4.3",
    "django-environ==0.11.2",
    "djangorestframework==3.15.2",
    "docker==7.1.0",
    "gunicorn==23.0.0",
    "PyYAML==6.0.2",
    "python-dateutil==2.9.0.post0",
]

[dependency-groups]
dev = [
    "black==24.4.2",
    "djlint==1.34.1",
    "isort==5.13.2",
    "pylint==3.3.1",
]

[tool.black]
line-length = 120
exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
profile = "black"
skip = "migrations"
filter_files = true

[tool.pylint]
ignore = ["migrations", "manage.py", ".venv", "venv", ".env", "env"]
disable = [
    "no-member", # Some members are created in runtime, pylint fails to detect such cases
    "line-too-long", # We already have this in black.
    "broad-exception-caught",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-many-ancestors", # django can't cope well with this one
    "too-few-public-methods", # django can't cope well with this one
    "fixme"
]
