# Generated by Django 5.2.17 on 2026-09-06 13:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(help_text='Name of your credential', unique=True, verbose_name='Label')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Dockerhub'), (2, 'Github Pat'), (3, 'Aws Ecr'), (4, 'Gitlab Pat'), (97, 'Generic Registry'), (98, 'Generic Git'), (99, 'Generic Http Auth')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(max_length=500)),
                ('cmd', models.CharField(blank=True, help_text='Command to execute', max_length=500)),
                ('parameters', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cron_rule', models.CharField(max_length=25)),
                ('cron_rule_hash', models.CharField(blank=True, db_index=True, max_length=200)),
                ('active', models.BooleanField(default=True, help_text='Active')),
                ('singleton', models.BooleanField(default=False, help_text='Selecting this option will make this schedule a singleton: only one instance will be allowed to run at any given time.')),
                ('sequential_failures', models.IntegerField(default=0)),
                ('env_vars', models.JSONField(blank=True, null=True)),
                ('image', models.CharField(max_length=500, verbose_name='Image')),
                ('cpu', models.IntegerField(blank=True, help_text='Number of CPUs', null=True)),
                ('memory', models.IntegerField(blank=True, help_text='Memory in MB', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, help_text='If you leave blank, will assume node default registry.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.credential', verbose_name='Credentials')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='node.node')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('state', models.JSONField(null=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.TextField(blank=True)),
                ('status_code', models.IntegerField(null=True)),
                ('provisioning', models.BooleanField(default=True)),
                ('exception_on_build', models.BooleanField(default=False)),
                ('exception_on_pull', models.BooleanField(default=False)),
                ('exception_on_run', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
