# Generated by Django 5.0.6 on 2024-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schedule_active_alter_schedule_cron_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.SlugField(max_length=500),
        ),
    ]
