# Generated by Django 5.0.6 on 2024-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(default="waiting", max_length=20),
        ),
    ]
