# Generated by Django 5.0.6 on 2024-07-14 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
