# Generated by Django 5.0.6 on 2024-07-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_job_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="log",
            field=models.TextField(blank=True),
        ),
    ]
