# Generated by Django 5.0.6 on 2024-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_job_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status_code",
            field=models.IntegerField(null=True),
        ),
    ]
