# Generated by Django 5.0.6 on 2024-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_job_status_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="exception_on_build",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="exception_on_pull",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="exception_on_run",
            field=models.BooleanField(default=False),
        ),
    ]
