# Generated by Django 5.0.6 on 2024-07-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_job_exception_on_build_job_exception_on_pull_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Dockerhub Token"),
                    (2, "Github Private Access Token"),
                    (3, "aws ECR (Elastic Container Registry)"),
                    (98, "generic git repository"),
                    (98, "generic registry"),
                    (99, "generic HTTP auth"),
                ],
                default=0,
            ),
        ),
    ]
