# Generated by Django 5.0.6 on 2024-07-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_credential_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="provisioning",
            field=models.BooleanField(default=True),
        ),
    ]
