# Generated by Django 5.0.6 on 2024-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_job_provisioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="cmd",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
