# Generated by Django 5.0.6 on 2024-10-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_schedule_cmd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Dockerhub"),
                    (2, "Github PAT"),
                    (3, "AWS ECR"),
                    (98, "generic git"),
                    (98, "generic registry"),
                    (99, "generic HTTP auth"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="name",
            field=models.SlugField(
                help_text="Name of your credential", unique=True, verbose_name="Label"
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="cmd",
            field=models.CharField(
                blank=True, help_text="Command to execute", max_length=500
            ),
        ),
    ]
