# Generated by Django 5.0.6 on 2024-10-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_credential_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credential",
            name="category",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Dockerhub"),
                    (2, "Github PAT"),
                    (3, "AWS ECR"),
                    (98, "generic git"),
                    (98, "generic registry"),
                    (99, "generic HTTP auth"),
                ],
                default=1,
            ),
        ),
    ]
