# Generated by Django 5.0.6 on 2024-10-05 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_credential_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                help_text="If you leave blank, will assume node default registry.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.credential",
                verbose_name="Credentials",
            ),
        ),
    ]
