# Generated by Django 5.0.6 on 2024-11-18 21:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_credential_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("host", models.CharField(max_length=250)),
                ("port", models.IntegerField(default=2375)),
                ("use_ssh", models.BooleanField(default=False)),
                ("secret", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="credential",
            name="category",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Dockerhub"),
                    (2, "Github Pat"),
                    (3, "Aws Ecr"),
                    (4, "Gitlab Pat"),
                    (97, "Generic Registry"),
                    (98, "Generic Git"),
                    (99, "Generic Http Auth"),
                ],
                default=1,
            ),
        ),
    ]
