# Generated by Django 5.0.6 on 2024-11-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_node_alter_credential_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Node",
        ),
    ]
