# Generated by Django 5.0.6 on 2025-03-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_delete_node"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="schedule",
            name="cpu",
            field=models.IntegerField(blank=True, help_text="Number of CPUs", null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="memory",
            field=models.IntegerField(blank=True, help_text="Memory in MB", null=True),
        ),
    ]
