# Generated by Django 5.2.17 on 2026-09-06 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_schedule_created_by'),
        ('node', '0002_node_unix_socket'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='node.node'),
        ),
    ]
