#!/bin/sh

set -e

echo "Running pre push hook!"
repository_path=$(git rev-parse --show-toplevel)

echo "Running Ruff lint checks.."
uv run ruff check "$repository_path"

echo "Checking Ruff formatting.."
uv run ruff format --check "$repository_path"

echo "Running tests"
export DJANGO_TEST=1
rm -rf "/tmp/cron.d/"
mkdir -p "/tmp/cron.d/"
uv run python "$repository_path"/manage.py test "$repository_path"/apps
exit 0
