#!/bin/sh

set -e

echo "Running pre push hook!"
repository_path=$(git rev-parse --show-toplevel)

echo "Running black.."
uv run black "$repository_path"/apps

echo "Running isort.."
uv run isort "$repository_path"/apps

echo "Running djlint"
uv run djlint --check "$repository_path"/apps

echo "Running pylint"
uv run pylint .

echo "Running tests"
export DJANGO_TEST=1
rm -rf "/tmp/cron.d/"
mkdir -p "/tmp/cron.d/"
uv run python "$repository_path"/manage.py test "$repository_path"/apps
exit 0
