#!/bin/sh

set -e

echo "Running pre push hook!"
repository_path=$(git rev-parse --show-toplevel)

echo "Running black.."
black "$repository_path"/apps

echo "Running isort.."
isort "$repository_path"/apps

echo "Running djlint"
djlint --check "$repository_path"/apps

echo "Running pylint"
pylint .

echo "Running tests"
python3 "$repository_path"/manage.py test "$repository_path"/apps
exit 0