name: Code quality control

on:
  push:

jobs:
  quality-control:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run quality checking
        run: |
          ./.hooks/pre-push
          ls
