# Generated by Django 5.0.6 on 2024-11-19 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("host", models.CharField(max_length=250)),
                ("port", models.IntegerField(default=2375)),
                ("use_ssh", models.BooleanField(default=False)),
                ("secret", models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
