# Generated by Django 5.2.17 on 2026-09-06 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('host', models.CharField(blank=True, max_length=250)),
                ('port', models.IntegerField(default=2375, null=True)),
                ('use_ssh', models.BooleanField(default=False)),
                ('secret', models.CharField(blank=True, max_length=500)),
                ('unix_socket', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
