# Generated by Django 5.2.17 on 2026-09-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='unix_socket',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
