# Generated by Django 5.2.17 on 2026-09-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_node_unix_socket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='unix_socket',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
