# Generated by Django 5.2.17 on 2026-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_node_unix_socket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='unix_socket',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
