# Generated by Django 5.2.17 on 2026-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_alter_node_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='port',
            field=models.IntegerField(default=2375, null=True),
        ),
    ]
